### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by lewisosborne** [jayamanikharyono/airflow-dag-action#33]
@jayamanikharyono 
(Duplicate of this comment: https://github.com/jayamanikharyono/airflow-dag-action/pull/32#issuecomment-1891809005)

Request for a new release (v2.5) of this repo to be made, so that recent updates can be included and it can be referenced properly in external workflows, i.e.:

`uses: jayamanikharyono/airflow-dag-action@v2.5`

Many thanks! 🙏

**Comment by jayamanikharyono** [comment]
Just released [v2.5](https://github.com/jayamanikharyono/airflow-dag-action/releases/tag/v2.5)
